# Generated by Django 3.2.7 on 2022-07-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0002_auto_20220704_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_types',
            old_name='types_cat',
            new_name='types_catigoriy',
        ),
    ]
