# Generated by Django 3.2.7 on 2022-07-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0003_rename_types_cat_test_types_types_catigoriy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options_A', models.CharField(max_length=50, verbose_name='Вориант А')),
                ('options_B', models.CharField(max_length=50, verbose_name='Вориант B')),
                ('options_C', models.CharField(max_length=50, verbose_name='Вориант C')),
                ('options_D', models.CharField(max_length=50, verbose_name='Вориант D')),
                ('answer', models.CharField(help_text='Напишите правильный вариант', max_length=10)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_platform.test_types', verbose_name='Тип тестов')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
