# Generated by Django 3.2.7 on 2022-07-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0004_test_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_question',
            name='question',
            field=models.TextField(verbose_name='Опишите Вопрос'),
        ),
    ]
